server:
  port: 8080

spring:
  h2:
    console:
      enable: true
      path: /h2

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:./test_db;MODE=MYSQL;AUTO_SERVER=TRUE
    username: sa
    password:
